[package]
name = "seify-hackrfone"
version = "0.1.0"
edition = "2021"
authors = ["Troy Neubauer <troy@foxhunter.ai>"]

[dependencies]
atomic_enum = "0.3.0"
futures-lite = "2.3.0"
log = "0.4.22"
num-complex = "0.4"
# nusb = { git = "https://github.com/kevinmehall/nusb.git" }
nusb = { path = "../nusb" }
thiserror = "1.0.63"

[dev-dependencies]
anyhow = "1.0.86"
env_logger = "0.11.5"
